DROP DATABASE IF EXISTS `korean_webapp`;
CREATE DATABASE `korean_webapp`;
USE `korean_webapp`;

CREATE TABLE IF NOT EXISTS vocabulary (
	item_id INT NOT NULL AUTO_INCREMENT,
    korean VARCHAR(8) CHARACTER SET utf8,
    english VARCHAR(49) CHARACTER SET utf8,
    PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS users (
	user_id  INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS flashcards (
	flashcard_id INT NOT NULL AUTO_INCREMENT,
    due_date DATE NOT NULL,
    priority INT NOT NULL,
    vocabulary_item_ref_id INT,
    FOREIGN KEY(vocabulary_item_ref_id) REFERENCES vocabulary(item_id),
    user_ref_id INT,
	FOREIGN KEY(user_ref_id) REFERENCES users(user_id),
    PRIMARY KEY (flashcard_id)
);



/*inserted from excel using sqlizer.io*/
INSERT INTO vocabulary(korean, english) VALUES ('피아노','piano'),
	('타월','towel'),
	('데이트','date, dating'),
	('메시지','message'),
	('휴가','vacation, holiday'),
	('영','spirit, zero'),
	('정도','degree'),
	('사례','case, example'),
	('테이블','table'),
	('평양','Pyongyang'),
	('주로','mainly'),
	('외할아버지','maternal grandfather'),
	('따로','separately'),
	('목걸이','necklace'),
	('행복','happiness'),
	('다르다','different'),
	('달러','dollar'),
	('풀','pool, grass'),
	('대한민국','Republic of Korea, South Korea'),
	('동물','animal'),
	('곧','soon'),
	('무','radish'),
	('된장국','soybean paste soup'),
	('모시다','take you, serve you  (honorific form)'),
	('취직하다','get a job'),
	('이제','now'),
	('덥다','hot'),
	('보내다','send, spend'),
	('올라가다','go up'),
	('하숙','boarding house, lodging house'),
	('잘못','mistake'),
	('이','this, tooth, 2'),
	('운동','exercise'),
	('똑같다','same'),
	('회색','grey'),
	('아빠','dad'),
	('프린트','print'),
	('크다','big, large'),
	('원하다','want, wish, desire'),
	('멋있다','cool, nice'),
	('누구','who'),
	('울리다','make cry, chime'),
	('저녁','dinner, evening, night'),
	('하다','do, say'),
	('스웨터','sweater'),
	('생각','thinking, thought'),
	('놀라다','be surprised'),
	('오월','May'),
	('언니','sister (as seen from the younger sister)'),
	('민속촌','folk village'),
	('골프','golf'),
	('일곱','7'),
	('태풍','typhoon'),
	('입','mouth'),
	('한국어','Korean language'),
	('신다','put on, wear'),
	('설명','explanation, description'),
	('까만색','black color'),
	('병원','hospital'),
	('켜다','turn on (the light, the power, etc.)'),
	('여덟','8'),
	('조선어','Korean language'),
	('끓이다','boil'),
	('직원','employee, staff'),
	('공항','airport'),
	('서쪽','west, western'),
	('아주머니','old lady, madame, aunt'),
	('꿈','dream'),
	('며칠','a few days, what date'),
	('요리','cooking, cuisine'),
	('빌리다','borrow, lend'),
	('개인','individual'),
	('축제','festival'),
	('치마','skirt'),
	('기분','feeling'),
	('어깨','shoulder'),
	('실례하다','be excused'),
	('쌓이다','stack up, pile up'),
	('점심','lunch'),
	('대','versus, large'),
	('서울역','Seoul station'),
	('떨어지다','drop'),
	('설날','Lunar New Year'),
	('텔레비전','TV'),
	('호주','Australia'),
	('국어','Korean language'),
	('샴푸','shampoo'),
	('굽다','bake'),
	('봉지','bag'),
	('별로','not really'),
	('일본사람','Japanese people'),
	('오전','morning, a.m.'),
	('규칙','rule'),
	('글쎄요','I do not know., well, I guess ~'),
	('조용하다','silent, quiet'),
	('쪽','side, page'),
	('그냥','just, as it is'),
	('반갑다','nice to meet, happy'),
	('빨간색','red color'),
	('가구','furniture'),
	('상품','product'),
	('호텔','hotel'),
	('이쪽','this way, here, this person'),
	('이틀','two days'),
	('장갑','gloves'),
	('예문','example, model sentence'),
	('나이','age, old'),
	('발표','announcement, presentation'),
	('시장','market'),
	('괜찮습니다','It''s fine.'),
	('칠','7'),
	('움직이다','move'),
	('성함','name'),
	('지난번','last time'),
	('갈비','Galvi, spareribs'),
	('정거장','station, depot'),
	('빵집','bakery'),
	('주차하다','park'),
	('조선말','Korean language'),
	('팀','team'),
	('시작되다','begin'),
	('가수','singer'),
	('공부하다','study'),
	('냄비','pot'),
	('피자','pizza'),
	('준비','preparation'),
	('교체','substitute, change'),
	('출발하다','depart'),
	('밑','bottom, below'),
	('늦잠','overslept, sleeping in late'),
	('아프리카','Africa'),
	('고맙습니다','Thank you'),
	('말씀','words, remarks'),
	('가게','store, shop'),
	('코','nose'),
	('층','layer, ~ floor'),
	('마치다','finish, end'),
	('하늘색','sky blue, light blue'),
	('돌아가다','return, go back'),
	('지키다','protect'),
	('손','hand'),
	('시험','exam, test'),
	('되다','become'),
	('바나나','banana'),
	('사장','CEO, the president'),
	('날짜','date'),
	('정리하다','straighten out, organize'),
	('삼촌','paternal uncle'),
	('학','crane'),
	('달력','calendar'),
	('목','neck, throat'),
	('아기','baby, toddler'),
	('복숭아','peach'),
	('님','Sir'),
	('미터','meter'),
	('일식','Japanese style, Japanese food'),
	('부치다','send, fry, transmit'),
	('사무실','office'),
	('토마토','tomato'),
	('인터넷','internet'),
	('이렇다','like this'),
	('아프다','painful, sick'),
	('매주','every week'),
	('정문','front door, main gate'),
	('부탁','request, please'),
	('후배','Junior'),
	('그런','then, such'),
	('대학교','university, college'),
	('화나다','angry'),
	('샤워하다','take a shower'),
	('중요','importance'),
	('영하','minus, below zero'),
	('서른','30'),
	('돼지','pig'),
	('문화','culture'),
	('배부르다','be full (I am full.)'),
	('엽서','postcard'),
	('안녕하세요','hi, hello'),
	('어떤','which, what'),
	('그거','it'),
	('모이다','gather, get together'),
	('세계','world'),
	('몽골','Mongolia'),
	('아주','very, completely'),
	('죽','bamboo, porridge'),
	('파티','party'),
	('사계절','four seasons'),
	('오른쪽','right side, right'),
	('인사하다','greet'),
	('지하','underground'),
	('어머님','mother'),
	('늘','always'),
	('간식','snack'),
	('북쪽','North'),
	('물론','sure, of course'),
	('환자','patient'),
	('수건','towel, washcloth'),
	('내리다','go down'),
	('비싸다','expensive'),
	('다음해','next year, following year'),
	('그때','then, at that time'),
	('포장','packing'),
	('십','10'),
	('뉴스','news'),
	('건물','building'),
	('물','water'),
	('멕시코','Mexico'),
	('광고','advertisement'),
	('구름','cloud'),
	('길','way, road'),
	('지나다','pass by'),
	('운동화','sports shoes'),
	('너','you'),
	('저곳','over there'),
	('조금','a little'),
	('정하다','choose, establish'),
	('선풍기','fan'),
	('수돗물','tap water'),
	('피','blood'),
	('반년','half a year'),
	('고모부','paternal uncle'),
	('시간','time'),
	('수박','watermelon'),
	('즐거워하다','have fun'),
	('편','side, episode'),
	('언제','when'),
	('열리다','be opened'),
	('남녀','men and women'),
	('처음','first, for the first time'),
	('고모','paternal aunt'),
	('별','star'),
	('스물','20'),
	('좁다','narrow'),
	('뉴욕','New York'),
	('알다','know'),
	('걸다','bet, call'),
	('의자','chair'),
	('막히다','be blocked, be clogged'),
	('외국인','foreigner'),
	('우리','we, us'),
	('느리다','slow'),
	('못하다','~ can not do'),
	('얇다','thin'),
	('걸어가다','walk (go)'),
	('그곳','there'),
	('인도','India'),
	('국','soup'),
	('날','day'),
	('그리다','draw'),
	('실례','excuse');
INSERT INTO vocabulary(korean, english) VALUES ('여동생','younger sister'),
	('선물','gift, present'),
	('그것','it'),
	('회사','company'),
	('어머니','mother'),
	('끝','end'),
	('거울','mirror'),
	('읽기','reading'),
	('도로','road'),
	('소금','salt'),
	('횡단보도','crosswalk'),
	('문장','sentence'),
	('벽','wall'),
	('부인','wife, Mrs.'),
	('목적','purpose'),
	('열','10'),
	('그래','Yes, Yeah'),
	('아줌마','old lady, madame, aunt'),
	('축구','football, soccer'),
	('쇼핑','shopping'),
	('동대문시장','Dongdaemun market'),
	('소파','sofa'),
	('연락처','contact information'),
	('가장','most'),
	('맞다','right, fit, correct'),
	('환영하다','welcome'),
	('비밀','secret'),
	('비누','soap'),
	('혼자','alone'),
	('나가다','go out, get out'),
	('줄','line, column, string'),
	('건너편','other side, opposite side'),
	('사탕','candy'),
	('계산하다','calculate'),
	('사월','April'),
	('구월','September'),
	('이모','maternal aunt'),
	('지난주','last week'),
	('떡','rice cake'),
	('칫솔','toothbrush'),
	('지갑','wallet'),
	('호랑이','tiger'),
	('드라마','drama'),
	('계획','plan'),
	('방법','way, method'),
	('간단하다','simple, easy'),
	('아까','earlier, while ago'),
	('색깔','color'),
	('잠시','for a bit, for a while, a little'),
	('푹','deeply'),
	('팔다','sell'),
	('오다','come'),
	('아니다','no'),
	('발음','pronunciation'),
	('누나','sister (as seen from the younger brother)'),
	('자기','myself, own'),
	('할인','sale, discount'),
	('반바지','shorts'),
	('차다','kick'),
	('오십','50'),
	('조용히','quietly'),
	('묻다','ask'),
	('짓다','build, create'),
	('합격','pass'),
	('쓰이다','be written, be used'),
	('미래','future'),
	('결혼하다','get married'),
	('잠깐','for a while, a little'),
	('때','time'),
	('거짓말','lie'),
	('짐','load, baggage'),
	('고르다','choose'),
	('수요일','Wednesday'),
	('간장','soy sauce'),
	('뭐','what'),
	('오랜만에','after a long time'),
	('부동산','real estate'),
	('전','all, before'),
	('보이다','show, look'),
	('그날','that day'),
	('아홉','9'),
	('자료','material, document'),
	('답장','reply'),
	('가깝다','close'),
	('방학','vacation'),
	('서점','bookstore'),
	('동전','coin'),
	('원피스','one-piece dress'),
	('축하합니다','congratulations'),
	('착하다','be good, friendly'),
	('싫어하다','dislike, hate'),
	('킬로미터','kilometer'),
	('사십','40'),
	('고향','hometown'),
	('독일','Germany'),
	('시골','countryside'),
	('이사','move, moving'),
	('주다','give'),
	('고등학생','high school student'),
	('알았습니다','I understood.'),
	('휴지통','trash can'),
	('고장','broken, malfunction'),
	('흐리다','cloudy'),
	('풀다','solve'),
	('웃다','laugh'),
	('과','division'),
	('노트','note'),
	('학교','school'),
	('예','yes'),
	('내려가다','go down'),
	('살다','live'),
	('이십','20'),
	('페이지','page'),
	('둘','2'),
	('높다','high'),
	('사이다','cider'),
	('표현','expression'),
	('화내다','get angry'),
	('미술','art'),
	('신발','shoes, footwear'),
	('국내','domestic'),
	('가족','family'),
	('일찍','early'),
	('목욕하다','take a bath'),
	('문제','problem'),
	('대학원생','postgraduate student, graduate student'),
	('넓다','wide'),
	('길다','long'),
	('팔십','80'),
	('기숙사','dormitory'),
	('수학','mathematics'),
	('붙이다','attach, stick'),
	('자신','myself, own'),
	('맛','flavor, taste'),
	('장마철','rainy season'),
	('파란색','blue color'),
	('그만','stop, finish'),
	('라면','ramen'),
	('옷장','closet'),
	('세탁기','washing machine'),
	('도쿄','Tokyo'),
	('사촌','cousin'),
	('일본','Japan'),
	('성','castle, last name'),
	('큰어머니','aunt'),
	('퇴근하다','leave the office'),
	('팔월','August'),
	('열다','open'),
	('세일하다','have a sale'),
	('남','south, man'),
	('고치다','fix'),
	('무섭다','scary'),
	('장','~ chapter(s), ~ sheet(s)'),
	('일본말','Japanese language'),
	('이름','name'),
	('주차장','parking lot'),
	('열심히','hard, enthusiastic'),
	('기타','other'),
	('걱정','anxiety, concern'),
	('관심','attention, interest'),
	('주황색','orange color'),
	('좋아하다','like'),
	('저희','we'),
	('이월','February'),
	('슈퍼마켓','supermarket'),
	('갖다','have'),
	('내','of mine, my'),
	('월세','monthly rent'),
	('음악가','musician'),
	('이렇게','like this, so, in this way'),
	('모자','hat'),
	('햇빛','sunshine, sunlight'),
	('돌아오다','come back, come home'),
	('커피숍','coffee shop'),
	('다녀오다','return, come back'),
	('사랑','love'),
	('이집트','Egypt'),
	('제가','I'),
	('출발','start, departure'),
	('하지만','but, however'),
	('그리고','and'),
	('사고','accident'),
	('달','month, moon'),
	('장소','place'),
	('구','9'),
	('깨다','wake up, crack, break'),
	('초','~second(s)'),
	('사원','temple, employee'),
	('적','enemy'),
	('나무','tree'),
	('볶다','fry'),
	('야채','vegetable'),
	('마늘','garlic'),
	('쓰레기','garbage'),
	('아버님','father'),
	('자리','seat, location'),
	('선생님','teacher'),
	('과학','science'),
	('슬퍼하다','sorrow, mourn'),
	('이것','this'),
	('있다','have, there'),
	('간','while'),
	('미술관','art gallery, art museum'),
	('만지다','touch'),
	('이곳','this place, here'),
	('출근하다','go to work'),
	('사다','buy'),
	('단점','disadvantage, shortcoming, drawback'),
	('김포공항','Gimpo International Airport'),
	('행사','event'),
	('일상생활','everyday life'),
	('특징','characteristic, feature'),
	('오','5'),
	('능력','ability'),
	('주스','juice'),
	('감기약','cold medicine'),
	('모르다','do not know'),
	('나쁘다','bad'),
	('친하다','close, familiar'),
	('질문','question'),
	('가지다','have'),
	('추억','memory'),
	('바꾸다','change'),
	('독서','reading'),
	('다니다','go, commute'),
	('직업','job, profession'),
	('여름','summer'),
	('경기','competition, game'),
	('주인','owner'),
	('옷','dress, clothes'),
	('유월','June'),
	('놓다','put'),
	('월','month'),
	('형님','big brother (honorific form)'),
	('남편','husband'),
	('어린이','child'),
	('들다','hold, enter'),
	('목소리','voice'),
	('서다','stand'),
	('비','rain'),
	('무슨','what'),
	('따라가다','follow'),
	('식사','meal'),
	('대답하다','answer, reply'),
	('힘','power'),
	('일본요리','Japanese food'),
	('작은아버지','uncle'),
	('간호사','nurse'),
	('국적','nationality, country of citizenship'),
	('유리','glass');
INSERT INTO vocabulary(korean, english) VALUES ('그러나','but, however'),
	('마흔','40'),
	('봉투','envelope'),
	('미리','in advance, beforehand'),
	('저녁식사','dinner'),
	('봄','spring'),
	('새','bird, new'),
	('외할머니','maternal grandmother'),
	('외롭다','lonely'),
	('프랑스','France'),
	('칠판','blackboard'),
	('시내','downtown, city, stream'),
	('편지','letter'),
	('된장','fermented soybean paste'),
	('오래간만입니다','Long time no see.'),
	('외삼촌','maternal uncle'),
	('미국','The United States'),
	('베트남','Vietnam'),
	('맞아요','That''s right.'),
	('춤','dance'),
	('기쁘다','happy'),
	('추석','Chusoku (Korean Thanksgiving Day)'),
	('당신','you'),
	('경찰관','police officer'),
	('한글','Hangul'),
	('백화점','department store'),
	('아버지','father'),
	('소풍','picnic, trip'),
	('형제','sibling'),
	('바람','wind'),
	('세탁소','dry cleaners, laundromat'),
	('지우개','eraser'),
	('가다','go'),
	('농구','basketball'),
	('교통','traffic'),
	('식탁','table'),
	('한강','Han River, Hangang'),
	('잘','well'),
	('일월','January'),
	('여권','passport'),
	('학년','grade, school year'),
	('내과','internal medicine'),
	('공간','space'),
	('시민','citizen'),
	('노래방','Karaoke shop'),
	('여행','travel'),
	('외국어','foreign language'),
	('동쪽','east'),
	('하늘','sky'),
	('에어컨','air conditioner'),
	('기름','oil, gasoline'),
	('방송국','broadcast stations'),
	('자다','sleep'),
	('거리','street'),
	('햄버거','hamburger'),
	('아저씨','uncle, mister'),
	('넥타이','necktie'),
	('점','point'),
	('밀가루','flour'),
	('어떻게','how'),
	('무역','trade'),
	('그동안','meantime, meanwhile, up to now'),
	('시간표','schedule, timetable'),
	('아이스크림','ice cream'),
	('연필','pencil'),
	('그치다','stop, end, cease'),
	('제목','title'),
	('해외','overseas'),
	('면도','razor, shaving'),
	('깎다','cut, shave'),
	('가요','song'),
	('싸우다','fight'),
	('급하다','hurry, urgent'),
	('내다','pay, put out'),
	('건강','health'),
	('처음 뵙겠습니다','Nice to meet you.'),
	('넘어지다','fall down, fall'),
	('잘하다','do well, good at'),
	('식당','restaurant, cafeteria'),
	('스키','ski, skiing'),
	('크리스마스','Christmas'),
	('대답','answer'),
	('사물','object, thing'),
	('눈','eye, snow'),
	('어울리다','look good on, befit'),
	('누가','who'),
	('김치','Kimchi'),
	('원','won (currency units of Korea)'),
	('약사','pharmacist'),
	('연예인','celebrity'),
	('동생','brother, sister'),
	('커피','coffee'),
	('끄다','turn off, extinguish, stop'),
	('지내다','stay, spend, live'),
	('두','two'),
	('점수','score, point'),
	('저분','that person'),
	('외출하다','go out'),
	('전공','major'),
	('걸리다','get caught, take (time)'),
	('청바지','blue jeans'),
	('바쁘다','busy'),
	('유학생','foreign student, international student'),
	('전기자동차','electric car'),
	('문구점','stationery store'),
	('출장','business trip'),
	('반지','ring'),
	('드리다','give'),
	('아뇨','no'),
	('여러분','everyone, ladies and gentlemen'),
	('속','inside'),
	('탤런트','entertainers'),
	('공짜','free'),
	('싫다','hate'),
	('기다리다','wait'),
	('꾸다','dream'),
	('기르다','cultivate, grow'),
	('요일','day of the week'),
	('다이어트','diet'),
	('다음달','next month'),
	('내용','content'),
	('한국요리','Korean cuisine'),
	('녹색','green'),
	('특별히','especially'),
	('시디','CD'),
	('비행장','airfield, airport'),
	('소화제','peptic, digestive'),
	('씩','each, every, per'),
	('홍차','black tea'),
	('닫히다','shut, close'),
	('시외','suburbs'),
	('뒤','rear, back'),
	('주부','housewife'),
	('떠나다','leave'),
	('고마웠습니다','Thank you (past tense)'),
	('중국집','Chinese restaurant'),
	('돕다','help'),
	('이상하다','strange, funny, weird'),
	('베이징','Beijing'),
	('배우','actor'),
	('검은색','black'),
	('자르다','cut'),
	('액세서리','accessory'),
	('엄마','mom'),
	('전화번호','phone number'),
	('현금','cash'),
	('축하','celebration'),
	('부드럽다','soft, friendly'),
	('싶다','want'),
	('영상','video'),
	('좋다','good'),
	('성격','personality'),
	('터미널','terminal'),
	('냉면','cold noodle'),
	('아래','bottom, under'),
	('세수하다','wash'),
	('스페인어','Spanish'),
	('받다','receive'),
	('댁','house'),
	('미안합니다','I''m sorry.'),
	('된장찌개','soybean paste stew'),
	('양말','socks'),
	('예약','reservation'),
	('찾아가다','go to visit'),
	('쓰다','write, use, wear (glasses)'),
	('사람','person, man'),
	('학기','semester'),
	('결정','decision'),
	('손님','customer'),
	('열차','train'),
	('생활','life'),
	('일본드라마','Japanese drama'),
	('뜨겁다','hot'),
	('여자','woman'),
	('우선','first'),
	('감사','thank'),
	('중요하다','important'),
	('벌써','already'),
	('확인하다','confirm, check'),
	('내일','tomorrow'),
	('사업가','entrepreneur, businessman'),
	('토요일','Saturday'),
	('참','really, very'),
	('가운데','middle'),
	('몸','body'),
	('중학교','middle school, Junior high school'),
	('산','mountain'),
	('한국사람','Korean people'),
	('술','alcohol, liquor'),
	('이용하다','use'),
	('모양','shape, form, style'),
	('발','foot, leg'),
	('마르다','dry'),
	('기자','reporter'),
	('불편하다','uncomfortable, inconvenient'),
	('디자인','design'),
	('통','barrel, ~ package(s)'),
	('사인하다','sign'),
	('로션','skin lotion'),
	('잊어버리다','forget'),
	('양식','form, western style'),
	('하얗다','white'),
	('맥주','beer'),
	('손수건','handkerchief'),
	('라디오','radio'),
	('펴다','spread, stretch'),
	('담배','tobacco'),
	('필요하다','need'),
	('맵다','spicy'),
	('칼','knife, cutlery, swords'),
	('빨갛다','red'),
	('결혼식','wedding ceremony'),
	('해','year, sun'),
	('신청서','application forms'),
	('네','yes, 4'),
	('소포','parcel'),
	('아무','any'),
	('수술하다','operate on for'),
	('분위기','#N/A'),
	('눈사람','snowman'),
	('여든','80'),
	('오징어','squid'),
	('입다','put on, wear'),
	('옆','side'),
	('어리다','young'),
	('부산','Busan'),
	('그림','drawing, picture'),
	('신문','newspaper'),
	('건강하다','be healthy'),
	('화장품','cosmetics'),
	('어느','which, how'),
	('직접','directly, direct'),
	('벌다','earn, make money'),
	('년','year'),
	('서류','document'),
	('디브이디','DVD'),
	('나타나다','appear'),
	('자동차회사','car company'),
	('주','week'),
	('것','that, thing, it'),
	('음료수','drink, soft drink'),
	('초등학교','elementary school'),
	('겨울','winter'),
	('인기스타','popular star'),
	('입원하다','hospitalize'),
	('초록색','green color'),
	('감동','sensation'),
	('정류장','station, bus stop'),
	('이모부','maternal uncle'),
	('씨','seed, Mr. ~');
INSERT INTO vocabulary(korean, english) VALUES ('프로그램','program'),
	('쉰','50'),
	('나다','occur, come out'),
	('사이즈','size'),
	('오랫동안','for a long time'),
	('재미있다','interesting'),
	('발전','development'),
	('남미','South America'),
	('종로','Jong-ro'),
	('태어나다','be born'),
	('낮','day, noon, during the day'),
	('보통','usually, normally, in general'),
	('시설','facility'),
	('인상','impression'),
	('아직','yet, still'),
	('초콜릿','chocolate'),
	('냄새','smell'),
	('육','6'),
	('그렇다','Yes, that''s it.'),
	('따르다','follow'),
	('끼다','put on, plug, (fog) rolls in'),
	('부장','director'),
	('느끼다','feel'),
	('달다','sweet'),
	('후','after'),
	('엘리베이터','elevator'),
	('샌드위치','sandwich'),
	('노래','song'),
	('맛있다','delicious'),
	('동네','town, neighborhood'),
	('중학생','middle school student'),
	('진달래','azalea'),
	('서울','Seoul'),
	('긴장되다','be nervous'),
	('사','4'),
	('그렇구나','well, I see.'),
	('제주도','Jeju Island'),
	('증세','symptom, medical condition'),
	('취미','hobby'),
	('앉다','sit'),
	('쉬다','rest'),
	('보다','see'),
	('전화','telephone'),
	('교회','church'),
	('떠들다','chatter, make a noise'),
	('가방','bag'),
	('지하철','subway'),
	('갈아타다','transfer'),
	('젓가락','chopsticks'),
	('개','dog, ~ piece(s)'),
	('넣다','put in'),
	('경기장','stadium, arena'),
	('벚꽃','cherry blossom'),
	('냉장고','refrigerator'),
	('배달','delivery'),
	('날씨','weather'),
	('껌','chewing gum'),
	('시원하다','cool, refresh'),
	('컵','cup'),
	('평일','weekday'),
	('호','No. ~'),
	('하루','one day'),
	('그램','gram'),
	('항상','always'),
	('시다','sour'),
	('허리','waist, hip'),
	('화가','artist, painter'),
	('둘째','second, the second of~'),
	('가을','autumn, fall'),
	('고추','red pepper'),
	('그러니까','so, because'),
	('도움','help, assistance'),
	('무겁다','heavy'),
	('홈페이지','home page'),
	('이런','this, such ~'),
	('지금','now'),
	('거의','almost, nearly'),
	('계단','stairs'),
	('서비스','service'),
	('부업','sideline'),
	('수저','chopsticks and a spoon'),
	('삼계탕','Samgyetang'),
	('책장','bookshelf'),
	('친척','relative'),
	('스케이트','skate'),
	('점심시간','lunchtime'),
	('와이셔츠','shirt'),
	('메뉴','menu'),
	('배고프다','hungry'),
	('초등학생','elementary student'),
	('이분','this person'),
	('어른','adult'),
	('대회','competition, tournament'),
	('아내','wife'),
	('나흘','four days'),
	('초대하다','invite'),
	('외국','foreign country'),
	('옷가게','clothing store'),
	('달걀','egg'),
	('월요일','Monday'),
	('변호사','lawyer'),
	('선수','player'),
	('만들다','make, create'),
	('학생','student'),
	('잠','slumbers, sleep'),
	('동양','eastern, orient'),
	('생일','birthday'),
	('요금','fee'),
	('자동차','car, automobile'),
	('열쇠','key'),
	('땀','sweat'),
	('메모','memo'),
	('고맙다','thank'),
	('첫','first'),
	('부르다','call, sing'),
	('서양','western, west'),
	('작다','small'),
	('지하철역','subway station'),
	('모르겠습니다','I don''t know.'),
	('조심하다','be careful, warn'),
	('달리다','run'),
	('제일','most'),
	('가르치다','teach'),
	('감자','potato'),
	('많다','many'),
	('안전하다','safe'),
	('덕분','thanks for, thanks to'),
	('그런데','by the way, however'),
	('쌀','rice'),
	('서로','each other, both'),
	('셋','3'),
	('적다','be few, write down'),
	('낚시','fishing'),
	('유명하다','famous'),
	('자주','often'),
	('전혀','not at all'),
	('나누다','share, divide'),
	('연휴','consecutive holidays'),
	('관계','relation'),
	('두껍다','thick'),
	('최고','best, the highest'),
	('브라질','Brazil'),
	('떡볶이','Toppogi'),
	('선택하다','choose, select'),
	('짜다','salty, make (the plan)'),
	('번호','number'),
	('한자','Chinese character'),
	('인사','greetings'),
	('그럼','then'),
	('저거','that'),
	('만화','comic book, cartoon'),
	('칠월','July'),
	('만일','if, should'),
	('가져가다','take away'),
	('매우','extremely, very'),
	('한번','once'),
	('위험하다','dangerous'),
	('빌딩','building'),
	('내가','I'),
	('빨리','quickly'),
	('좀더','a little more'),
	('김','seaweed'),
	('유행','trend'),
	('올림픽','olympic'),
	('마지막','last'),
	('수첩','note, notebook'),
	('즐기다','enjoy, have fun'),
	('두다','put'),
	('약','about, medicine'),
	('가져오다','bring'),
	('통하다','pass, lead'),
	('소설가','novelist'),
	('전자사전','electronic dictionary'),
	('형','brother (as seen from the younger brother)'),
	('운동선수','athlete'),
	('거기','there'),
	('창문','window'),
	('국제','international'),
	('나중','later, after'),
	('치료하다','treat'),
	('회의','conference'),
	('다섯','5'),
	('취소하다','cancel'),
	('공무원','public official'),
	('우산','umbrella'),
	('기차','train'),
	('생각하다','think'),
	('부부','couple, husband and wife, married couple'),
	('들','field, ~s,'),
	('추다','dance'),
	('무궁화','rose of sharon'),
	('휴대전화','cell phone, mobile phone'),
	('철','iron, season'),
	('바이올린','violin'),
	('학원','academy, school'),
	('색','color'),
	('책상','desk'),
	('하얀색','white color'),
	('나빠지다','spoil, deteriorate'),
	('남자','man'),
	('더럽다','dirty'),
	('손가락','finger'),
	('신청하다','put in for, apply for'),
	('귤','mandarin orange'),
	('부지런하다','diligent'),
	('뒤쪽','behind, back, towards the rear'),
	('다른','other ~, another ~, different ~'),
	('오빠','brother (as seen from the younger sister)'),
	('어떻다','how'),
	('얼굴','face'),
	('무엇이','what'),
	('닭','chicken, hen'),
	('금요일','Friday'),
	('입학','admission'),
	('싸다','cheap, wrap'),
	('아름답다','beautiful'),
	('아파트','apartment, mansion'),
	('꺼내다','take out'),
	('어서','hurry, quickly'),
	('화장하다','makeup'),
	('극장','theater, cinema'),
	('귀엽다','cute'),
	('필통','pencil case'),
	('가위','scissors'),
	('그렇게','like that, so'),
	('설탕','sugar'),
	('다리','bridge, leg, foot'),
	('바다','sea'),
	('잘생기다','handsome'),
	('대학원','graduate school'),
	('저','that'),
	('바라다','hope'),
	('소고기','beef'),
	('생신','birthday  (honorific form)'),
	('결정하다','decide'),
	('밤','night'),
	('세우다','set up, formulate'),
	('장마','rainy season'),
	('곱다','beautiful'),
	('무척','very'),
	('왜','why'),
	('감기','cold'),
	('동아리','club, group'),
	('엔','yen'),
	('종일','all day'),
	('주소','address'),
	('직장','workplace'),
	('깨끗하다','clean'),
	('삼월','March'),
	('지난달','last month');
INSERT INTO vocabulary(korean, english) VALUES ('인천','Incheon'),
	('기사','article, driver, engineer'),
	('마시다','drink'),
	('여러','various, many'),
	('무료','free'),
	('바지','pants'),
	('휴지','toilet paper'),
	('지방','fat, region'),
	('침대','bed'),
	('얘기하다','talk'),
	('요르단','Jordan'),
	('시계','clock'),
	('관광하다','travel, sightsee'),
	('감','persimmon'),
	('찾아오다','come to visit'),
	('말하기','speaking'),
	('독서실','reading room'),
	('삼거리','intersection, three-way intersection'),
	('파랗다','blue'),
	('양','amount, sheep'),
	('딸기','strawberry'),
	('애','child'),
	('경험','experience'),
	('위하다','for, in favor of, for the sake of'),
	('일요일','Sunday'),
	('차리다','prepare, arrange'),
	('강','river'),
	('남학생','male student'),
	('주무시다','sleep, rest'),
	('경찰서','police office'),
	('갈비탕','Galbitang, spareribs soup'),
	('눈싸움','staring contest, snowball fight'),
	('순서','order, turn'),
	('읽다','read'),
	('절대','never, absolutely'),
	('장점','advantage'),
	('일','work, 1, day'),
	('등산화','hiking boots, climbing shoes'),
	('강아지','puppy'),
	('주말','weekend'),
	('벗다','take off (clothes, shoes)'),
	('그','it'),
	('바르다','right, paint, wear'),
	('우체국','post office'),
	('뜻','meaning'),
	('근처','nearby, neighborhood'),
	('감동하다','be impressed'),
	('저렇게','like that, in that way'),
	('슬프다','sad'),
	('요즘','nowadays, around this time, lately'),
	('경복궁','Gyeongbokgung'),
	('우리나라','our country, South Korea'),
	('그릇','bowl, container, tableware'),
	('피곤하다','tired'),
	('지다','lose'),
	('대사관','embassy'),
	('그들','them, they'),
	('빨래','laundry, wash'),
	('수업','class, lesson'),
	('하나','1'),
	('생기다','form, arise'),
	('박물관','museum'),
	('글','post, sentence, character'),
	('채소','vegetable'),
	('스타킹','stockings'),
	('반','half, group'),
	('씻다','wash'),
	('정말','really, truly'),
	('아니요','no'),
	('도착하다','arrive'),
	('캐나다','Canada'),
	('잔','glass, ~ cup(s)'),
	('더','more'),
	('스타','star'),
	('표','table, ticket'),
	('운전하다','drive'),
	('교실','classroom'),
	('간단히','simply'),
	('끝내다','finish'),
	('책','book'),
	('군인','soldier, military personnel'),
	('계속','continue'),
	('포도','grape'),
	('춥다','cold'),
	('아침','morning, breakfast'),
	('소개','introduction'),
	('탁구','table tennis'),
	('모레','the day after tomorrow'),
	('밖','out, outside'),
	('과자','snack'),
	('콧물','snot, nasal discharge'),
	('숙제','homework'),
	('방송','broadcast'),
	('고양이','cat'),
	('이메일','e-mail'),
	('국수','noodle'),
	('주위','around'),
	('공중전화','payphone, public phone'),
	('시작','start'),
	('넷','4'),
	('팔리다','sell, be sold'),
	('기억하다','remember'),
	('웬일','for some reason,  What was it?'),
	('돈','money'),
	('부탁하다','beg, ask'),
	('학생증','student ID card'),
	('등산','hiking, mountain-climbing'),
	('사거리','intersection, four corners'),
	('고속버스','express bus'),
	('수영복','swimsuit'),
	('배우다','learn'),
	('집','house, shop'),
	('치과','dentist, dentistry'),
	('팔','8'),
	('영어회화','English conversation'),
	('재료','material'),
	('꽃','flower'),
	('따뜻하다','warm'),
	('뿐','only'),
	('작년','last year'),
	('종이','paper'),
	('우유','milk'),
	('소리','sound, voice'),
	('아이','child'),
	('싱겁다','not salty'),
	('예순','60'),
	('재킷','jacket'),
	('올려놓다','put on, place'),
	('자전거','bicycle'),
	('화요일','Tuesday'),
	('구십','90'),
	('없이','without'),
	('동안','during, between'),
	('사전','dictionary'),
	('카드','card'),
	('잃어버리다','lose'),
	('남동생','younger brother'),
	('해외여행','overseas trip'),
	('권','~ book(s)'),
	('인터뷰하다','interview'),
	('칠십','70'),
	('교과서','textbook'),
	('중식','Chinese cuisine'),
	('듣다','listen'),
	('친구','friend'),
	('노력하다','endeavor, strive'),
	('계절','season'),
	('축하하다','celebrate'),
	('우표','stamp'),
	('또','in addition, again'),
	('따라오다','come with, follow'),
	('오렌지','orange'),
	('마음','mind, feeling'),
	('생선','fish'),
	('한복','Hanbok, Korean traditional clothes'),
	('값','price'),
	('인','sign, ~ person(s)'),
	('방','room'),
	('대화','conversation, dialogue'),
	('점심식사','lunch'),
	('닦다','wipe, polish'),
	('빠르다','fast'),
	('곳','place'),
	('감다','close ~ (eyes)'),
	('금연','no smoking'),
	('등','etc, back'),
	('옛날','a long ago, olden days'),
	('올해','this year'),
	('건너가다','cross (a road)'),
	('습관','habit'),
	('번','~ time(s)'),
	('구하다','save, seek, get'),
	('반찬','side dish'),
	('설거지','washing dishes, dish-washing'),
	('대학생','college student'),
	('음식','food, cooking'),
	('만','only, ten thousand'),
	('비디오','video'),
	('고추장','Kochujang, red pepper paste'),
	('이유','reason'),
	('몸살','sickness, disease that comes from fatigue'),
	('설렁탕','Seolleongtang'),
	('잡지','magazine'),
	('청소기','vacuum cleaner'),
	('붙다','stick, pass a test'),
	('시끄럽다','noisy'),
	('낮다','low'),
	('러시아','Russia'),
	('사진','picture, photo'),
	('교통사고','traffic accident'),
	('빵','bread'),
	('킬로그램','kilogram'),
	('머리','head, hair'),
	('갑자기','suddenly'),
	('응','Yeah (answer)'),
	('과일','fruit'),
	('일어나다','rise, stand, occur'),
	('눕다','lie down, sleep'),
	('반갑습니다','Nice to meet you.'),
	('구두','shoes'),
	('찾다','find, visit'),
	('결혼','marriage'),
	('모두','all, everyone'),
	('심하다','severe, terrible'),
	('대학','university, college'),
	('중심','center'),
	('교수','professor'),
	('산책','walk'),
	('카메라','camera'),
	('그러면','then, if so'),
	('물어보다','ask'),
	('배구','volleyball'),
	('핸드폰','cell phone, mobile phone'),
	('씹다','chew, bite'),
	('모으다','collect, gather'),
	('예쁘다','pretty, beautiful'),
	('안녕하십니까','hello'),
	('밥','rice, meal'),
	('느낌','feeling'),
	('다음','next, after'),
	('결과','result'),
	('차','car, tea'),
	('필름','film'),
	('알맞다','fit, appropriate'),
	('태권도','Taekwondo'),
	('영어','English'),
	('틀리다','wrong'),
	('감사드립니다','thank you'),
	('공휴일','public holiday'),
	('약국','pharmacy'),
	('기간','term, period'),
	('센티미터','centimeter'),
	('복잡하다','complicated, crowded'),
	('멀다','far, distant, long'),
	('잔치','party, feast'),
	('노랗다','yellow'),
	('대부분','mostly, almost'),
	('잊다','forget'),
	('말','word, talk'),
	('시청','city hall'),
	('노래하다','sing'),
	('올라오다','come up'),
	('남대문시장','Namdaemun market'),
	('겨울방학','winter vacation'),
	('패션','fashion'),
	('빨다','suck, do laundry'),
	('십일월','November'),
	('감사하다','thank, appreciate'),
	('찍다','pierce, take (a photo), press'),
	('여보세요','hello');
INSERT INTO  vocabulary(korean, english) VALUES ('설악산','Mt. Seorak'),
	('안다','embrace, cradle'),
	('남기다','leave'),
	('밝다','bright'),
	('휴일','holiday'),
	('돼지고기','pork'),
	('섬','island'),
	('택시','taxi'),
	('코트','coat'),
	('가슴','chest, breast'),
	('목욕','bath, bathing'),
	('갈색','brown'),
	('안','within, not ~'),
	('영화관','movie theater'),
	('데리다','bring, take along'),
	('딸','daughter'),
	('위치','location, position'),
	('유학','study abroad'),
	('출구','exit'),
	('회사원','employee'),
	('많이','a lot of, many'),
	('꼭','exactly, absolutely'),
	('아가씨','Miss, daughter'),
	('하숙집','boarding house, lodging house'),
	('명절','holidays, annual events'),
	('인형','doll'),
	('왜냐하면','because'),
	('선배','elder, senior'),
	('구경하다','take a look'),
	('이해하다','understand'),
	('할아버지','grandfather'),
	('그렇습니다','That''s right.'),
	('여러가지','several, various'),
	('조카','nephew'),
	('다시','again'),
	('병','illness, ~ bottle(s)'),
	('행복하다','happy'),
	('십이월','December'),
	('첫째','first'),
	('영화배우','movie star'),
	('즐겁다','fun, be pleasant'),
	('뜨다','rise, open (the eyes)'),
	('사랑하다','love'),
	('인삼','ginseng'),
	('거실','living room'),
	('덮다','cover'),
	('실수','mistake, failure'),
	('음악','music'),
	('의미','meaning'),
	('도착','arrival'),
	('이거','this'),
	('아시아','Asia'),
	('같다','same'),
	('자장면','Jajangmyeon'),
	('정보','information'),
	('재미없다','not funny, uninteresting'),
	('뵙다','meet'),
	('감사합니다','thank you'),
	('들어가다','go in, enter'),
	('스키장','ski resort'),
	('이야기하다','talk'),
	('지각','tardy, being late'),
	('상관','relation'),
	('중','medium, during'),
	('치약','toothpaste'),
	('사이','between, while'),
	('인구','population'),
	('짧다','short'),
	('지하도','underpass'),
	('안내하다','guide, invite'),
	('수영','swimming'),
	('이용','usage'),
	('얼마나','how much'),
	('가볍다','light'),
	('연세','age  (honorific form)'),
	('놀다','play'),
	('수도','capital, water supply'),
	('어머','oh, well'),
	('단어','word'),
	('유럽','Europe'),
	('키','key, height'),
	('말씀하다','talk'),
	('경치','view, landscape'),
	('피다','bloom'),
	('짜리','a value (won coin)'),
	('깨지다','chip, crack, break'),
	('아랍어','Arabic'),
	('주변','around'),
	('보도','sidewalk, report'),
	('월급','monthly salary'),
	('쌀밥','cooked rice'),
	('각','each'),
	('먹다','eat'),
	('시','city, time'),
	('잡다','catch, grab, hold'),
	('점퍼','jacket'),
	('티셔츠','t-shirt'),
	('사용하다','use'),
	('계란','egg'),
	('사과','apple'),
	('오래','long, much'),
	('의사','doctor'),
	('불다','blow (wind or whistle, musical instruments, etc.)'),
	('가격','price'),
	('비행기','airplane'),
	('소개하다','introduce'),
	('준비하다','prepare'),
	('때문','because, for ~, so~'),
	('맑다','clear, clean'),
	('잃다','lose'),
	('없다','none, no, not'),
	('육십','60'),
	('공원','park'),
	('배','ship, stomach, pear'),
	('닭고기','chicken'),
	('내년','next year'),
	('중국','China'),
	('바뀌다','be changed'),
	('계시다','be, exist (honorific form)'),
	('문','door, gate'),
	('볶음밥','fried rice'),
	('기침','cough'),
	('자유','freedom'),
	('케이크','cake'),
	('운동하다','exercise'),
	('카페','cafe, coffee shops'),
	('감자탕','Gamjatang, potato soup'),
	('운동장','playground, athletic field'),
	('도와주다','help'),
	('급','class, grade'),
	('무릎','knee'),
	('백','100'),
	('운동복','sportswear, gym clothes'),
	('인기','popularity'),
	('주문하다','order'),
	('영국','The United Kingdom'),
	('두부찌개','tofu soup'),
	('걸어오다','walk (come)'),
	('옮기다','move, transfer, translate'),
	('영화표','movie ticket'),
	('과거','past'),
	('어디','where'),
	('무엇','what'),
	('버스','bus'),
	('한국','Korea'),
	('일하다','work'),
	('천','1000'),
	('삼','3'),
	('소식','news'),
	('약속','appointment, promise'),
	('고기','meat'),
	('좀','a little'),
	('생각되다','be considered, it seems~'),
	('골목','alley'),
	('건너다','cross over'),
	('삼십','30'),
	('파','wave, green onion'),
	('큰아버지','uncle'),
	('고프다','hungry'),
	('펜','pen'),
	('시작하다','start, begin'),
	('말하다','say, talk'),
	('맞습니다','That''s right.'),
	('콧노래','humming'),
	('똑바로','upright, straight'),
	('개나리','forsythia'),
	('공부','study'),
	('차갑다','cold'),
	('특히','especially, in particular'),
	('맞은편','across, the other side, opposite'),
	('떡국','rice cake soup'),
	('깜짝','startled, surprised'),
	('분','~ person(s), ~ minute(s)'),
	('목요일','Thursday'),
	('질문하다','ask a question'),
	('장미','rose'),
	('약간','slightly, a little'),
	('무용','dance'),
	('도서관','library'),
	('수영장','swimming pool'),
	('게임','game'),
	('드시다','eat (honorific form)'),
	('무리','swarm, unreasonable'),
	('새벽','dawn, late at night, early morning'),
	('공연','show, public performance'),
	('연습하다','practice'),
	('금주','abstinence, temperance'),
	('매다','tie'),
	('전하다','tell'),
	('오늘','today'),
	('어제','yesterday'),
	('죄송하다','sorry'),
	('크기','size'),
	('이따가','later'),
	('은행','bank'),
	('공','ball'),
	('전화기','telephone'),
	('역','station'),
	('그렇지만','nevertheless, but'),
	('건배','cheers, toast'),
	('뛰다','run'),
	('바로','immediately, soon, just'),
	('종류','kind, type'),
	('오후','afternoon'),
	('누르다','press down, push'),
	('비빔밥','Bibimbap, mixed rice'),
	('신','god, new'),
	('춤추다','dance'),
	('꽃집','florist'),
	('경찰','police'),
	('사흘','3 days'),
	('틀다','turn on (the switch)'),
	('부모','parents'),
	('그중','among them'),
	('닮다','resemble'),
	('셋째','third'),
	('종업원','employee'),
	('녹차','green tea'),
	('불','fire, electrical light'),
	('공기','air'),
	('조선','shipbuilding, Korea'),
	('청소하다','sweep, clean'),
	('알리다','inform'),
	('더운물','hot water'),
	('주사','injection'),
	('그래서','so, thus'),
	('숟가락','spoon'),
	('저쪽','there, over there'),
	('외숙모','maternal aunt'),
	('스트레스','stress'),
	('듣기','listening, hearing'),
	('영화','movie'),
	('피우다','smoke, bloom'),
	('퍼센트','percent'),
	('조사하다','investigate'),
	('센터','center'),
	('웃기다','funny, make someone laugh'),
	('다','all, whole'),
	('중국어','Chinese'),
	('기온','temperature'),
	('일흔','70'),
	('할머니','grandmother'),
	('절','~ section(s), temple'),
	('비슷하다','similar, like'),
	('사진기','camera'),
	('미안하다','sorry'),
	('필요','necessity'),
	('붓다','pour'),
	('화장실','restroom, toilet, lavatory'),
	('바닷가','beach');
INSERT INTO  vocabulary(korean, english) VALUES ('살','flesh, ~ year(s) old'),
	('점원','clerk'),
	('아침식사','breakfast'),
	('줄다','shrink, decrease'),
	('입구','entrance'),
	('빼다','remove, pull, pull out'),
	('잠자다','sleep, go to bed'),
	('울다','cry'),
	('만나다','meet'),
	('기뻐하다','glad, delight'),
	('편하다','comfortable, easy, convenient'),
	('찌개','stew, soup'),
	('다치다','hurt'),
	('한국드라마','Korean drama'),
	('공책','notebook, note'),
	('남북','north and south'),
	('들어오다','come in, enter'),
	('다음주','next week'),
	('흰색','white color'),
	('질','quality'),
	('남쪽','south'),
	('일주일','one week'),
	('아마','maybe, perhaps'),
	('새로','newly'),
	('당근','carrot'),
	('한국말','Korean language'),
	('천천히','slowly'),
	('아흔','90'),
	('독서하다','read'),
	('괜찮다','be okay'),
	('잡수시다','eat (honorific form)'),
	('강좌','lecture'),
	('불고기','Bulgogi, grilled meat'),
	('매일','everyday'),
	('눈물','tear'),
	('새우','shrimp'),
	('시키다','make someone do, order'),
	('양파','onion'),
	('끝나다','finish, end'),
	('일기','diary'),
	('김치찌개','Kimchi stew'),
	('양복','suit'),
	('어렵다','difficult'),
	('함께','together'),
	('테니스','tennis'),
	('한식','Korean cuisine'),
	('그쪽','there, the person'),
	('어저께','yesterday'),
	('콩','bean, soy'),
	('졸업하다','graduate'),
	('반달','half-moon'),
	('오랜만','after a long time'),
	('얼음','ice'),
	('두부','tofu'),
	('나라','country'),
	('일본어','Japanese language'),
	('배탈','stomachache'),
	('닫다','close'),
	('김밥','Kimbab'),
	('너무','too, very'),
	('고등학교','high school'),
	('자연','nature'),
	('아들','son'),
	('부엌','kitchen'),
	('경주','Gyeongju'),
	('여기저기','here and there'),
	('썰다','chop, cut'),
	('자','character, Here we go.'),
	('소설','novel'),
	('쓰기','writing, dictation'),
	('또는','or'),
	('송이','bunch, flower, cluster'),
	('월드컵','world cup'),
	('도시','city'),
	('작은어머니','aunt'),
	('늘다','gain, increase'),
	('노란색','yellow color'),
	('여행사','travel agency, travel firm'),
	('그저께','day before yesterday'),
	('지도','map'),
	('카레','curry'),
	('만두','dumpling'),
	('이해','understanding'),
	('넘다','exceed, more than'),
	('금방','soon, a little while ago'),
	('아침밥','breakfast'),
	('넷째','fourth'),
	('상처','wound, scratch'),
	('앞','front, previous'),
	('어젯밤','last night'),
	('오르다','climb'),
	('가끔','sometimes'),
	('쯤','about, around ~'),
	('상자','box'),
	('오래간만','after a long time'),
	('내려오다','come down'),
	('명','~ person(s)'),
	('스포츠','sport'),
	('오이','cucumber'),
	('일어서다','get up, stand up'),
	('일기예보','weather forecast'),
	('먼저','first, first of all, before'),
	('여기','here'),
	('어둡다','dark'),
	('책임','responsibility'),
	('설명하다','explain'),
	('물건','stuff, thing'),
	('걱정하다','worry'),
	('젊다','young'),
	('책방','bookstore'),
	('촬영하다','take a picture'),
	('맛없다','not delicious'),
	('박수','clap, applause'),
	('나오다','come out, appear'),
	('태국','Thailand'),
	('메다','shoulder, carry'),
	('죽다','die'),
	('볼펜','ballpoint pen'),
	('국립','nationalestablished, state'),
	('쉽다','easy'),
	('걷다','walk'),
	('마리','~ animal(s), ~ head(s)'),
	('등산복','mountaineering clothing'),
	('안경','glasses'),
	('이상','more than, strange'),
	('졸업','graduation'),
	('가지','branch'),
	('미용실','beauty salon'),
	('악기','musical instrument'),
	('콜라','Coke'),
	('한','one, one of the ~'),
	('역사','history'),
	('이야기','story'),
	('아니오','no'),
	('연습','practice'),
	('발가락','toe(s)'),
	('통장','bank book, (deposit) passbook'),
	('그분','his, the person'),
	('현재','now, current'),
	('음반','record'),
	('은행원','bank clerk'),
	('화','anger'),
	('늦다','late, delay'),
	('저것','that'),
	('친절하다','be kind'),
	('코피','nosebleed'),
	('담그다','dip, pickle'),
	('위','top, up'),
	('귀','ear'),
	('어떻습니까?','How is it?'),
	('오리','duck'),
	('타다','ride, get on'),
	('모임','meeting, gathering'),
	('나','I'),
	('야구','baseball'),
	('밀리다','be shaved, be pushed'),
	('여섯','6'),
	('언제나','always, anytime'),
	('몇','a few, a number of'),
	('버리다','abandon, throw away'),
	('시월','October'),
	('왼쪽','left'),
	('저기','there, over there'),
	('컴퓨터','computer, PC'),
	('블라우스','blouse'),
	('까맣다','black'),
	('여학생','female student'),
	('소','small, cow'),
	('이번','this time'),
	('주머니','pocket, pouch'),
	('같이','together');
